-- Price Table: To store price aggregation from different sources
CREATE TABLE Price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    crypto_pair VARCHAR(10) NOT NULL,
    bid_price DECIMAL(20,8) NOT NULL,
    ask_price DECIMAL(20,8) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

--ShedLock Table: to keep information about scheduler locks
CREATE TABLE shedlock (
  name VARCHAR(64),
  lock_until TIMESTAMP(3) NULL,
  locked_at TIMESTAMP(3) NULL,
  locked_by VARCHAR(255),
  PRIMARY KEY (name)
)